spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sipf/config-service-data
          clone-on-start: true
server:
  port: 8888
security:
  user:
    name: admin
    password: password
encrypt:
  key-store:
    location: classpath:keystore.jks
    password: letmein
    alias: testkey
    secret: changeme
